

label_names = [
            "O",
            "B-rule_1",
            "B-rule_2",
            "B-rule_3",
            "B-rule_4",
            "B-rule_5",
            "B-rule_6",
            "B-rule_7",
            "B-rule_8",
            "B-rule_9",
            "B-rule_10",
            "B-rule_11",
            "B-rule_12",
            "B-rule_13",
            "B-rule_14",
            "B-rule_15",
            "B-rule_16",
            "B-rule_17",
            "B-rule_18",
            "B-rule_19",
            "B-rule_20",
            "B-rule_21",
            "B-rule_22",
            "B-rule_23",
            "B-rule_24",
            "B-rule_25",
        ]